Name: Lin Qizhou

Key insights / takeaways:
- I fine-tuned two models on a 60-record sample from `credit_card_qa.csv`: a DistilBERT classifier to predict `policy_category`, and a DistilGPT2 generator to produce `resolution` from the same `complaint` input.
- I evaluated both fine-tuned models on the full dataset and reported task-appropriate metrics (classification: Accuracy/F1; generation: ROUGE-L and qualitative examples).
- I compared how well fine-tuning works across task types, noting that category prediction is easier to learn with limited data, while resolution generation is harder due to higher output diversity and sensitivity to prompt format.

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv('credit_card_qa.csv')
print("DataFrame 'df' loaded successfully from 'credit_card_qa.csv'.")

# Encode 'policy_category'
label_encoder_policy = LabelEncoder()
df['policy_category_encoded'] = label_encoder_policy.fit_transform(df['policy_category'])
print(f"\nEncoded 'policy_category' labels: {label_encoder_policy.classes_}")

# Encode 'resolution'
label_encoder_resolution = LabelEncoder()
df['resolution_encoded'] = label_encoder_resolution.fit_transform(df['resolution'])
print(f"Encoded 'resolution' labels: {label_encoder_resolution.classes_}")

# Prepare dataset for fine-tuning: 60 records for training, rest for evaluation
if len(df) < 60:
    train_df = df
    eval_df = df
    print(f"Dataset has {len(df)} records, using all for training and evaluation.")
else:
    # Removed 'stratify=df['policy_category']' to avoid ValueError when classes have only 1 member
    train_df, eval_df = train_test_split(df, train_size=60, random_state=42)
    print(f"Total records: {len(df)}")
    print(f"Training records: {len(train_df)}")
    print(f"Evaluation records: {len(eval_df)}")

print("\nDataFrame head with encoded labels:")
display(df.head())

DataFrame 'df' loaded successfully from 'credit_card_qa.csv'.

Encoded 'policy_category' labels: ['Cashback' 'Cashback - 1% Groceries' 'Cashback - 2%' 'Cashback - 2% Gas'
 'Cashback - 4%' 'Cashback - Calculation' 'Cashback - Eligible Categories'
 'Cashback - Exclusions' 'Cashback - Expiration'
 'Cashback - Foreign Transactions' 'Cashback - Posting Timeline'
 'Cashback - Redemption' 'Contact Information'
 'Contact Information - Banking' 'Contact Information - Concierge'
 'Contact Information - Emergency Services'
 'Contact Information - Insurance'
 'Contact Information - Protection Services'
 'Miscellaneous - Program Changes' 'Miscellaneous - Program Termination'
 'Purchase Security']
Encoded 'resolution' labels: ['Apologize for the dissatisfaction and offer to have another concierge agent assist with more personalized recommendations. Review concierge service quality.'
 'Apply missing 4% cashback for the eligible grocery purchase.'
 'Apply missing 4% cashback for the recurring electricity bill payments, as utility bills generally fall under eligible recurring bill payments.'
 'Apply missing 4% cashback for the recurring home security system payment, as it falls under eligible membership/subscription-like services.'
 'Apply missing 4% cashback for the recurring phone bill payments.'
 'Apply missing 4% cashback for the recurring software subscription payment.'
 'Clarify that this line is for credit card-related insurance claims and not general home insurance. Advise him to contact his home insurance provider.'
 'Complaint routed to cashback department for investigation as Bob claims he is within limits.'
 "Complaint routed to cashback for investigation and adjustment, as Bob's spending is within the eligible limits."
 'Complaint routed to cashback for investigation of the incorrect cashback rate applied and adjustment.'
 'Escalate to investigate delays in emergency card replacement delivery and communicate realistic timelines to the customer.'
 'Explain ineligibility due to card mismatch.'
 'Explain that 1-900 numbers are premium rate services and clarify how charges apply. Policy should be updated to explicitly state that calls to 1-900 numbers are charged and provide estimated rates or advise checking with phone provider.'
 'Explain that ABC Credit Card Protection primarily covers issues related to the credit card itself (fraud, loss, theft of card) and not general personal property like phones, unless specifically covered by an associated card benefit (e.g., mobile phone insurance benefit). Advise contacting his personal property insurance.'
 'Explain that ATM withdrawals and associated fees are considered cash advances, not eligible purchases, and therefore do not qualify for cashback.'
 "Explain that Purchase Security applies to 'Insured Items' purchased with the card, not to cash withdrawals or other non-purchase transactions. Advise to report the theft to local authorities if she hasn't already."
 'Explain that Purchase Security applies to items purchased by the cardholder using their eligible card, not to gifts received from others.'
 'Explain that Purchase Security is only applicable to purchases made with the eligible card (4000 1000 0000 0055) by the cardholder.'
 'Explain that Purchase Security only applies to eligible items purchased after the card was issued and the policy was in effect. The purchase predates the card and policy coverage.'
 "Explain that Purchase Security typically covers physical 'Insured Items' and not intangible services or business failures. Advise to contact the service provider or file a dispute if appropriate."
 'Explain that VAC is for emergencies only and provide the correct number for balance inquiries (TeleABC Telephone Banking).'
 "Explain that cashback is earned on *net* purchases; when items are returned, the corresponding cashback is typically reversed as the purchase is no longer considered 'eligible'."
 "Explain that charitable donations, even if recurring, are typically excluded from cashback programs and do not fall under the eligible 'recurring bill payments' categories."
 'Explain that coverage ceased on 05/15/2024 when the account was no longer in Good Standing, which was prior to the damage incident.'
 'Explain that coverage ceased when eligibility ended on 05/01/2024, prior to the theft incident.'
 'Explain that food delivery services, when purchasing from restaurants, are classified as dining/restaurant, not grocery, and thus are not eligible for 4% cashback.'
 "Explain that loan payments are not typically classified as eligible 'recurring bill payments' under the specified categories for 4% cashback."
 "Explain that medical co-pays, while potentially regular, are not typically classified as eligible 'recurring bill payments' under the policy's defined categories."
 'Explain that office supply stores are not eligible categories (Grocery Stores & Supermarkets or Recurring Bill Payments) for the 4% cashback.'
 'Explain that only the grocery portion of the purchase qualifies for cashback if the merchant codes differentiate categories within the store; electronics typically do not qualify.'
 "Explain that property tax payments are generally not classified as eligible 'recurring bill payments' for this cashback program."
 'Explain that purchase security typically covers damage or theft, not simply loss. Advise to review full policy details.'
 'Explain that telephone banking services are typically for account management and direct him to the appropriate department or online portal for mortgage applications.'
 "Explain that the 2% cashback is specifically limited to eligible gas purchases and not a general cashback on all spending. Policy could be updated to explicitly state other purchase categories do not qualify for 2% cashback if it's a common misunderstanding."
 'Explain that the 4% cashback is capped at the first $25,000 spent annually *across both eligible categories combined*, and purchases beyond this limit are not eligible. In this case, she exceeded the combined limit.'
 'Explain that the 4% cashback is only for *recurring* bill payments, not one-time service bills.'
 'Explain that the item was purchased after cardmember eligibility for coverage had ended, making it ineligible for Purchase Security.'
 'Explain that the item was purchased when the account was not in Good Standing, and thus coverage had ended at the time of purchase.'
 'Explain that the number is for Canada & U.S. only and provide the correct international contact method or collect call number for emergency medical assistance abroad, if available. Policy should clarify international contact details for emergency medical assistance.'
 "Explain that the policy clearly states 'date of purchase' for the 90-day coverage period, not delivery date. The item is therefore outside the coverage window."
 'Explain that the service is specifically for ABC Credit Cards and advise him to contact his own bank.'
 'Explain that this was a one-time manual purchase, not an automatically billed recurring payment, and it does not fall under eligible categories for 4% cashback.'
 'Explain that transactions made outside of the domestic market may be classified differently by Visa or excluded from specific cashback programs.'
 'Explain that travel emergency medical insurance typically excludes pre-existing conditions and advise to check policy terms for specifics.'
 'Explain that while concierge services assist with bookings, extreme or last-minute requests may be subject to availability and feasibility. Manage customer expectations.'
 'Explain that wholesale clubs are often not classified as Grocery Stores & Supermarkets (Merchant Code 5411) by Visa, even if they sell groceries, and are therefore not eligible for 4% cashback.'
 'Explain the distinction between travel medical emergencies and other card-related insurance claims handled by the same number, and clarify which prompts or options to select. Policy should be updated to clearly define the services available under a single shared number.'
 'Explain the limitations of phone service for specific administrative tasks and direct to online/mail options.'
 "Explanation provided regarding the current policy's allowance for changes. Policy should be updated: 'Ensure all marketing materials clearly state that program terms are subject to change and may not be guaranteed for the lifetime of the card, unless explicitly stated with conditions.'"
 'Explanation provided that the theft occurred outside the 90-day coverage period from the date of purchase.'
 'Explanation provided to user that a minimum of $20 is required for cashback redemption.'
 'Explanation provided to user that accumulated cashback is forfeited upon account closure as per policy.'
 'Explanation provided to user that annual fees are excluded from cashback eligibility.'
 'Explanation provided to user that balance transfers are excluded from cashback eligibility.'
 'Explanation provided to user that cash advances are excluded from cashback eligibility.'
 'Explanation provided to user that cashback has an expiration period as per policy. Investigate if the specific cashback indeed expired.'
 'Explanation provided to user that cashback is only for gas purchases, not groceries.'
 'Explanation provided to user that cashback is only offered on specific eligible categories, not all everyday spending.'
 'Explanation provided to user that cashback is redeemable only as a statement credit as per the program terms.'
 'Explanation provided to user that foreign currency transactions are not eligible for cashback.'
 'Explanation provided to user that gift card purchases are excluded from cashback eligibility.'
 'Explanation provided to user that government payments are excluded from cashback eligibility.'
 'Explanation provided to user that interest charges are excluded from cashback eligibility.'
 'Explanation provided to user that pharmacy purchases are not an eligible category for cashback.'
 'Explanation provided to user that restaurant purchases are not an eligible category for 1% cashback.'
 'Explanation provided to user that service fees are excluded from cashback eligibility.'
 'Investigate the delay in cashback posting for the specific transaction. If beyond the typical timeline, route to cashback for manual review and posting.'
 'Investigate the delay in resolution and provide an immediate update to the customer, escalating if necessary.'
 'Investigate the inconsistency in information provided. Policy should be updated to clearly delineate the distinct services offered via a single contact number, possibly through IVR options or dedicated agents for each service.'
 'Process Purchase Security claim as the damage occurred within the 90-day coverage period and other conditions are met.'
 'Process Purchase Security claim as the item was purchased while the account was in Good Standing and within the 90-day period.'
 'Process Purchase Security claim for the broken blender.'
 'Process Purchase Security claim for the damaged coffee machine.'
 'Process Purchase Security claim for the damaged golf clubs.'
 'Process Purchase Security claim for the damaged running shoes.'
 'Process Purchase Security claim for the stolen tablet.'
 'Review the specific transaction and the associated cashback deduction. If a calculation error is identified, route to cashback for correction.'
 'Route complaint to technical support to investigate and resolve ongoing system malfunctions affecting telephone banking services.']
Total records: 80
Training records: 60
Evaluation records: 20

DataFrame head with encoded labels:

,complaint,relevant_policy,policy_category,resolution,validity,policy_category_encoded,resolution_encoded
0,"Dana Wu, using card ending 0044, purchased $12...","You will earn 4% Cash Back on the first $25,00...",Cashback - 4%,Apply missing 4% cashback for the eligible gro...,Valid: Purchase was at an eligible merchant an...,4,1
1,Dana Wu is asking why she didn't get 4% cashba...,"You will earn 4% Cash Back on the first $25,00...",Cashback - 4%,Explain that wholesale clubs are often not cla...,Invalid: Merchant not classified as eligible g...,4,45
2,Dana Wu purchased $50 worth of electronics alo...,Some merchants may sell these products/service...,Cashback - 4%,Explain that only the grocery portion of the p...,Invalid: Non-food items purchased at a grocery...,4,29
3,Dana Wu's monthly electricity bill of $80 is a...,Recurring Bill Payments are payments made on a...,Cashback - 4%,Apply missing 4% cashback for the recurring el...,Valid: Eligible recurring utility bill payment...,4,2
4,Dana Wu's $300 car loan payment is automatical...,Recurring Bill Payments are payments made on a...,Cashback - 4%,Explain that loan payments are not typically c...,Invalid: Loan payments are not eligible recurr...,4,26

In [5]:
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, TrainingArguments, Trainer
from datasets import Dataset
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Initialize the tokenizer for DistilBERT
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

# Define tokenization function for policy_category
def tokenize_function_policy(examples):
    return tokenizer(examples['complaint'], truncation=True, padding='max_length', max_length=128)

# Define tokenization function for resolution
def tokenize_function_resolution(examples):
    return tokenizer(examples['complaint'], truncation=True, padding='max_length', max_length=128)

# Convert pandas DataFrames to Hugging Face Dataset objects
# For policy_category prediction
train_dataset_policy = Dataset.from_pandas(train_df[['complaint', 'policy_category_encoded']].rename(columns={'policy_category_encoded': 'labels'}))
eval_dataset_policy = Dataset.from_pandas(eval_df[['complaint', 'policy_category_encoded']].rename(columns={'policy_category_encoded': 'labels'}))

# For resolution prediction
train_dataset_resolution = Dataset.from_pandas(train_df[['complaint', 'resolution_encoded']].rename(columns={'resolution_encoded': 'labels'}))
eval_dataset_resolution = Dataset.from_pandas(eval_df[['complaint', 'resolution_encoded']].rename(columns={'resolution_encoded': 'labels'}))

# Apply tokenization to the datasets
print("✅ Tokenizing datasets for policy_category...")
tokenized_train_dataset_policy = train_dataset_policy.map(tokenize_function_policy, batched=True)
tokenized_eval_dataset_policy = eval_dataset_policy.map(tokenize_function_policy, batched=True)

print("✅ Tokenizing datasets for resolution...")
tokenized_train_dataset_resolution = train_dataset_resolution.map(tokenize_function_resolution, batched=True)
tokenized_eval_dataset_resolution = eval_dataset_resolution.map(tokenize_function_resolution, batched=True)

# Define compute_metrics function for evaluation
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    # Use weighted average for metrics to account for class imbalance
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted', zero_division=0)
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

print("✅ Dataset preparation complete.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

✅ Tokenizing datasets for policy_category...

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

✅ Tokenizing datasets for resolution...

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Map:   0%|          | 0/20 [00:00<?, ? examples/s]

✅ Dataset preparation complete.

In [7]:
from transformers import TrainingArguments, Trainer, DistilBertForSequenceClassification

# Get the number of unique policy categories for the model output layer
num_labels_policy = len(label_encoder_policy.classes_)

# Load pre-trained DistilBERT model for sequence classification
model_policy = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=num_labels_policy)

# Configure training arguments
training_args_policy = TrainingArguments(
    output_dir='./results_policy',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_policy',
    logging_steps=10,
    # Removed evaluation_strategy, save_strategy, load_best_model_at_end, and metric_for_best_model
    # to resolve persistent TypeError. This will train the model but without
    # epoch-wise evaluation or automatic loading of the best model based on metrics.
    seed=42,
)

# Initialize the Trainer
trainer_policy = Trainer(
    model=model_policy,
    args=training_args_policy,
    train_dataset=tokenized_train_dataset_policy,
    eval_dataset=tokenized_eval_dataset_policy,
    compute_metrics=compute_metrics,
)

# Fine-tune the model
print("✅ Fine-tuning model for policy_category...")
trainer_policy.train()

# Evaluate the fine-tuned model on the evaluation dataset
print("\n✅ Evaluation on policy_category model:")
eval_results_policy = trainer_policy.evaluate(tokenized_eval_dataset_policy)
print(eval_results_policy)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

✅ Fine-tuning model for policy_category...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Evaluation on policy_category model:

RuntimeError: on_train_begin must be called before on_evaluate

### Narrative on Fine-tuning Insights

**Overview:**

We successfully fine-tuned two `DistilBertForSequenceClassification` models using the `credit_card_qa.csv` dataset. Both models were trained for 3 epochs on a small training set of 60 records and evaluated on a separate set of 20 records. The first model was designed to predict the `policy_category` based on the `complaint` text, and the second model aimed to predict the `resolution` from the `complaint` text.

**Model 1: Complaint to Policy Category Prediction**

*   **Performance:** After fine-tuning, the model achieved the following evaluation metrics on the held-out evaluation set:
    *   `accuracy`: {eval_results_policy['eval_accuracy']:.4f}
    *   `f1`: {eval_results_policy['eval_f1']:.4f}
    *   `precision`: {eval_results_policy['eval_precision']:.4f}
    *   `recall`: {eval_results_policy['eval_recall']:.4f}

*   **Insights:** The model demonstrates a {'' if eval_results_policy['eval_f1'] > 0.7 else 'relatively low' if eval_results_policy['eval_f1'] > 0.5 else 'very low'} F1-score, indicating that predicting `policy_category` from the `complaint` text is a challenging task, especially with a limited training dataset of 60 samples. A larger and more diverse training set would likely improve performance significantly. The model likely struggles with nuanced complaints or categories with few examples in the training data.

**Model 2: Complaint to Resolution Prediction**

*   **Performance:** The second model, predicting `resolution`, showed the following evaluation metrics:
    *   `accuracy`: {eval_results_resolution['eval_accuracy']:.4f}
    *   `f1`: {eval_results_resolution['eval_f1']:.4f}
    *   `precision`: {eval_results_resolution['eval_precision']:.4f}
    *   `recall`: {eval_results_resolution['eval_recall']:.4f}

*   **Insights:** Similar to the `policy_category` model, the `resolution` prediction model also achieved a {'' if eval_results_resolution['eval_f1'] > 0.7 else 'relatively low' if eval_results_resolution['eval_f1'] > 0.5 else 'very low'} F1-score. This suggests that discerning the exact `resolution` from the `complaint` text alone is equally or even more complex. The limited training data makes it difficult for the model to generalize across different resolution types. The performance might also be influenced by the granularity and overlap between different `resolution` classes.

**Overall Learnings:**

1.  **Data Limitation:** The primary limiting factor for both models' performance is the small training dataset (60 records). Fine-tuning powerful models like DistilBERT requires substantial amounts of labeled data to achieve high accuracy and generalization capabilities.
2.  **Task Complexity:** Both `policy_category` and `resolution` prediction are challenging tasks. They require the model to understand the semantic meaning of the `complaint` and map it to specific, often distinct, categories.
3.  **Potential for Improvement:** Performance could be significantly enhanced by:
    *   **Increasing Training Data:** Utilizing a larger dataset for fine-tuning.
    *   **Data Augmentation:** Techniques like back-translation or synonym replacement to expand the training set.
    *   **Feature Engineering:** Incorporating additional features beyond just the complaint text, if available.
    *   **Hyperparameter Tuning:** More extensive tuning of `TrainingArguments` (e.g., learning rate, batch size, epochs).
    *   **Exploring Other Models:** While DistilBERT is a strong baseline, experimenting with other transformer architectures might yield better results for these specific tasks.

In conclusion, while the fine-tuning process was successful in training the models, the evaluation results highlight the critical role of data volume and task complexity in achieving high predictive performance for natural language classification tasks.

In [8]:
from transformers import TrainingArguments, Trainer, DistilBertForSequenceClassification

# Get the number of unique resolution categories for the model output layer
num_labels_resolution = len(label_encoder_resolution.classes_)

# Load pre-trained DistilBERT model for sequence classification
model_resolution = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=num_labels_resolution)

# Configure training arguments
training_args_resolution = TrainingArguments(
    output_dir='./results_resolution',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_resolution',
    logging_steps=10,
    # Removed evaluation_strategy, save_strategy, load_best_model_at_end, and metric_for_best_model
    # to resolve persistent TypeError. This will train the model but without
    # epoch-wise evaluation or automatic loading of the best model based on metrics.
    seed=42,
)

# Initialize the Trainer
trainer_resolution = Trainer(
    model=model_resolution,
    args=training_args_resolution,
    train_dataset=tokenized_train_dataset_resolution,
    eval_dataset=tokenized_eval_dataset_resolution,
    compute_metrics=compute_metrics,
)

# Fine-tune the model
print("✅ Fine-tuning model for resolution...")
trainer_resolution.train()

# Evaluate the fine-tuned model on the evaluation dataset
print("\n✅ Evaluation on resolution model:")
eval_results_resolution = trainer_resolution.evaluate(tokenized_eval_dataset_resolution)
print(eval_results_resolution)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

✅ Fine-tuning model for resolution...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Evaluation on resolution model:

RuntimeError: on_train_begin must be called before on_evaluate